// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12.04.2025, 17:45:40
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/user/Desktop/DevX-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX-main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX-main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX-main/plugins/**/*.{js,ts,mjs}","C:/Users/user/Desktop/DevX-main/composables/**/*.{js,ts,mjs}","C:/Users/user/Desktop/DevX-main/utils/**/*.{js,ts,mjs}","C:/Users/user/Desktop/DevX-main/pages/faq.vue","C:/Users/user/Desktop/DevX-main/pages/about.vue","C:/Users/user/Desktop/DevX-main/pages/index.vue","C:/Users/user/Desktop/DevX-main/pages/contacts.vue","C:/Users/user/Desktop/DevX-main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX-main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/DevX-main/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;